apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: https://F321EC7882AFC522661B4228B2C645DF.gr7.us-east-1.eks.amazonaws.com
            namespace: default
          - cluster: https://F321EC7882AFC522661B4228B2C645DF.gr7.us-east-1.eks.amazonaws.com
            namespace: kube-system
          - cluster : https://F321EC7882AFC522661B4228B2C645DF.gr7.us-east-1.eks.amazonaws.com
            namespace: argocd
  template:
    metadata:
      name: '{{namespace}}-my-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/denisdugar/NPG.git
        targetRevision: HEAD
        path: .
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'

