apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1
  tags:
    env: test-env
    app: npg-test

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

iam:
  withOIDC: true

vpc:
#  clusterEndpoints:
#    publicAccess: false
#    privateAccess: true
  id: vpc-0d2d753c2fa916692
  subnets:
    private:
      us-east-1a: { id: subnet-05f055fa8e5fefb87 }
      us-east-1b: { id: subnet-00cf3e0dacfb8d4cb }

nodeGroups:
  - name: test-group
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    subnets:
      - subnet-05f055fa8e5fefb87
      - subnet-00cf3e0dacfb8d4cb
    labels:
      role: worker
    tags:
      env: test
      app: npg-test