apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterconfigs.eksctl.io
spec:
  group: eksctl.io
  scope: Cluster
  names:
    plural: clusterconfigs
    singular: clusterconfig
    kind: ClusterConfig
    shortNames:
      - cc
  versions:
    - name: v1alpha5
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object

